language: node_js
node_js:
  - 12
install: npm ci
script:
  - npm run lint-ci
  - npm run build
before_deploy:
  - export TAG=travis-$TRAVIS_COMMIT-$TRAVIS_BUILD_NUMBER
  - export ELASTIC_BEANSTALK_LABEL="$TAG-$(env TZ=Asia/Singapore date "+%Y%m%d%H%M%S")"
deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    region: ap-southeast-1
    app: $STAGING_APP_NAME
    env: $STAGING_DEPLOY_ENV
    bucket: $STAGING_BUCKET_NAME
    only_create_app_version: false
    on:
      branch: $STAGING_BRANCH
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    region: ap-southeast-1
    app: $PROD_APP_NAME
    env: $PROD_DEPLOY_ENV
    bucket: $PROD_BUCKET_NAME
    only_create_app_version: false
    on:
      branch: $PROD_BRANCH
